### ISSUE TITLE
I would like to translate your articles in my native language Bengali

### ISSUE THREAD

**Issue by jaamaal95** [thomaslombart/thomaslombart.com#125]
Hey Lombart,

I have read your articles and that's very cool writing. I would like to translate some of your articles to my native language Bengali.

First I would go with => [Writing Blazing Fast HTML Code](https://thomaslombart.com/writing-blazing-fast-HTML-code/) this one.

**Comment by thomaslombart** [comment]
Hi Jamal, thanks for the kind words!

There's no problem in translating them as long as you mention me and my blog post as the original source 🙂

**Comment by jaamaal95** [comment]
Thanks for your prompt reply.

I will make PR when I will finish my translation if you wish to add your site as translated version link of your blog.
