### ISSUE TITLE
Tu vas bien ouesh

### ISSUE THREAD

**Issue by ikinzMartin** [thomaslombart/thomaslombart.com#17]
Ca fait un bail,

Tu vas bien?
Jai compris que tu as travaillé dans l'équipe de Lola à Decat?
Hmu on peut se prendre un verre !

Bisous,
Marti Vasilev (ton binome de L2)

**Comment by thomaslombart** [comment]
Hello 👋 

L'issue m'était totalement sorti de la tête 😅 
Ouais, ça fait un bout de temps. J'ai bien bossé à Decath sur un chatbot.

Si tu veux plus parler, voilà mon adresse mail : thomas.lombart@hey.com 
Ce sera plus pratique 😉
